### Create - Valid User
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "yourpassword",
  "name": "testName"
}


### Login - Invalid User
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "wrong@example.com",
  "password": "badpassword"
}

### Login - Valid User
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "yourpassword"
}





### access token from successful login
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc0OTA3MDc4NCwiZXhwIjoxNzQ5MDc0Mzg0fQ.WrnztKitw23Ua_B_C-rJ26NhnF3UhMtmDOL3tL6EwSw

### GET - Get Profile
GET http://localhost:3000/api/v1/users/me
Authorization: Bearer {{token}}

### PATCH - Update Profile
PATCH http://localhost:3000/api/v1/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "updatedTestName"
}

### DELETE - current user
DELETE http://localhost:3000/api/v1/users/me
Authorization: Bearer {{token}}

### POST -- custom exercise
POST http://localhost:3000/api/v1/exercises-catalog/custom
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "name": "test press2",
  "primaryMuscle": "Chest",
  "equipment": "Barbell",
  "description": "Isolated chest press on bench"
}

### Get default + custom
GET http://localhost:3000/api/v1/exercises-catalog?custom=true
Authorization: Bearer {{token}}

### Get only default
GET http://localhost:3000/api/v1/exercises-catalog
Authorization: Bearer {{token}}




# As an ADMIN user (you’ll need to either seed an admin or manually set a user’s role via Prisma Studio):

### Login - Valid ADMIN User
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpass"
}

###
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMzLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzUxMTU4NTE4LCJleHAiOjE3NTExNjIxMTh9.5x7P1AJkF_Sa73IalHq32AKPujdwNmVdJT4ZhU5UigI

### GET - Template Workouts
GET http://localhost:3000/api/v1/template-workouts
Authorization: Bearer {{adminToken}}

###
GET http://localhost:3000/api/v1/exercises-catalog/search?term=press
Authorization: Bearer {{adminToken}}

###
GET http://localhost:3000/api/v1/exercises-catalog/65
Authorization: Bearer {{adminToken}}

###
POST http://localhost:3000/api/v1/exercises-catalog/default
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "name": "Goblet Squat",
  "primaryMuscle": "Legs",
  "equipment": "Dumbbell",
  "description": "Front squat with dumbbell held at chest"
}



