### Create - Valid User
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "yourpassword",
  "name": "testName"
}


### Login - Invalid User
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "wrong@example.com",
  "password": "badpassword"
}

### Login - Valid User
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "yourpassword"
}
### access token from successful login
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc0OTA3MDc4NCwiZXhwIjoxNzQ5MDc0Mzg0fQ.WrnztKitw23Ua_B_C-rJ26NhnF3UhMtmDOL3tL6EwSw

### GET - Get Profile
GET http://localhost:3000/api/v1/users/me
Authorization: Bearer {{token}}

### PATCH - Update Profile
PATCH http://localhost:3000/api/v1/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "updatedTestName"
}

### DELETE - current user
DELETE http://localhost:3000/api/v1/users/me
Authorization: Bearer {{token}}

### POST -- custom exercise
POST http://localhost:3000/api/v1/exercises-catalog/custom
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "aaaaaa",
  "primaryMuscle": "Biceps",
  "equipment": "Dumbbell",
  "description": "Isolated bicep curl with support bench"
}

### Get default + custom
GET http://localhost:3000/api/v1/exercises-catalog?custom=true
Authorization: Bearer {{token}}

### Get only default
GET http://localhost:3000/api/v1/exercises-catalog
Authorization: Bearer {{token}}


